# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a1678613349855f35b3146185d5e7a60305cc5ce8252707aa1bee3b04991a6aaf0a0188a8c534348ffe80022e1f5879232f728bac646016d809a8c1e7d7878ab

test:
  secret_key_base: 7133f80dfca051f90067d177d69ff422901fa62e0ee9f690b70271fcdbb5b208df868d15389adc5f627b6c7b0058dd3e1f93e3ac55be0665983744712968fc3b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
